title: Thu Huong (Gina)
logo: /assets/img/headshot_circle.png
description: I am a Finance graduate with a keen interest in Data Analysis, passionate about exploring numbers and deriving meaningful insights. 
theme: jekyll-theme-minimal
